name: Test and publish
run-name: "Branch: ${{ github.head_ref || github.ref_name	}}, event ${{ github.event_name	}}, commit sha ${{ inputs.SHA || github.sha }} by @${{ github.actor }}"
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    needs: run-jest-test
    if: github.head_ref == 'main' || github.ref_name == 'main' # run this job only for the main branch
    environment: "deploy docker"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          tag: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Set short sha
        id: sha_short
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "sha_short=$calculatedSha" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ steps.meta.outputs.tags }}-${{ steps.sha_short.outputs.sha_short }}"
          labels: ${{ steps.meta.outputs.labels }}
