name: Build and Publish docker image
run-name: "Publish docker image, tag $GITHUB_REF_NAME sha ${{ inputs.SHA || github.sha }}"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: self-hosted
    environment: ci
    outputs: 
      tag: ${{ steps.test.outputs.mytag }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          tag: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,event=tag,pattern={{raw}}
    
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # -${{ steps.sha_short.outputs.sha_short }}

      - name: test
        id: test
        run: |
          echo "mytag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT  
      - 
        name: Build and push
        id: capture-tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          platforms: "linux/amd64,linux/arm64"
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend-cache:latest
          # cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend-cache:latest,mode=max
      

  modify_image_tag:
    needs: build
    runs-on: ubuntu-latest
    environment: ci
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_PASSWORD: ${{ secrets.GITOPS_TOKEN }}
      RUN_NUMBER: ${{ github.run_number }}
      TAG: ${{ needs.build.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        name: Changing the deployment of git repo
        with:
          repository: DoTruong1/vdt-frontend-config-repo
          token: ${{ secrets.GITOPS_TOKEN }}
          ref: main
      - name: modify image tag
        run: |
          echo $TAG
          echo “Working Directory: $(pwd)”
          sed -i.bak '/^image:/,/^[^ ]/ s/^\( *\)tag:.*/\1tag: "'"$TAG"'"/' values.yaml
          # Print values.yaml for debugging after changes
          # echo “After modification:”
          # cat values.yaml  

      - name: publish new image
        run: |
          git config user.email 'aa@gmail.com'
          git config user.name 'DoTruong'
          rm values.yaml.bak
          git add values.yaml
          git commit -m "Update image tag by Github Actions Job change manifest: ${{ github.run_number }}"
          git push 
      
         
